criaCartao(
'MEDICINA',
'QUAL A FUNÇÃO DO CORAÇÃO?',
'BOMBEAR SANGUE PARA O CORPO'
)
criaCartao(
'GEOGRAFIA',
'QUAL A CAPITAL DO BRASIL',
'BRASILIA'
)
criaCartao(
    'EDUCAÇÃO FINANCEIRA',
    'O QUE SIGNIFICA CDB?',
    'CREDITO DE DEPOSITO BANCARIO'
)